project:
  type: website
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!projects"
  resources:
    - projects/dsan-5000/_site
    - projects/dsan-5100/_site

website:
  title: "Courtney Green"
  favicon: "images/cg-favicon.png"
  navbar:
    right:
      - href: about.qmd
        text: About
      - text: "Projects"
        menu: 
          - text: "Probabilistic Modeling of Prosecutorial Misconduct and Over-Policing in Chicago"
            href: projects/dsan-5000/_site/index.html
          - text: "Quantitative Analysis of Maternal Health Indicators and Reproductive Policy Variation"
            href: projects/dsan-5100/_site/index.html
          - text: "Data Driven Exploration of Humanitarian Aid Worker Vulnerability"
            href: https://dsan-viz2025.github.io/ 
          - text: "Modeling Voter Turnout and Partisan Lean in the 2024 U.S. Presidential Election"
            href: images/ML_Models_for_County-Level_Analysis_and_Voter_Turnout.pdf
            target: _blank
      - text: "Experience"
        href: experience.qmd

      - text: "Curriculum Vitae"
        href: images/Green_CV_2025.pdf
        target: _blank

      - icon: globe
        href: https://native-land.ca/

  page-footer:  
      left: >-
        &#169; 2025 Courtney Green &#8729; Made with [Quarto](https://quarto.org)

format:
  html:
    theme: 
      - lux
      - styles/courtney-theme.scss
    toc: true
    page-layout: full 
    include-in-header:
      - text: |
          <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" rel="stylesheet">
