---
title: "About"
toc: false
format:
  html: 
    css: styles/about.css
---

<ul class="fa-ul">
   <li><span class="fa-li"><i class="fa-solid fa-location-dot"></i></span> Washington, D.C.</li>
</ul>

I’m a data scientist and policy analyst based in Washington, D.C., pursuing my M.S. in Data Science & Analytics at Georgetown University. With a foundation in public policy from the University of Virginia, I focus on using machine learning and predictive analytics to inform equitable, evidence-based decisions. My work bridges technical rigor with social impact, especially around systemic inequality and sustainability.

## Objective 
To continue developing my expertise in data science and analytics by applying my skills in predictive modeling, data engineering, and machine learning to real-world challenges. I aim to leverage my technical knowledge and creative problem-solving abilities to drive meaningful, data-informed decisions and contribute to innovative, collaborative projects in dynamic environments.


## Education

<ul class="fa-ul">
  <li>
    <span class="fa-li"><i class="fa-solid fa-graduation-cap"></i></span>
    <strong>M.S. in Data Science & Analytics</strong> ∙ Georgetown University ∙ 2026
  </li>
  <li>
    <span class="fa-li"><i class="fa-solid fa-graduation-cap"></i></span>
    <strong>B.A. in Public Policy & Leadership</strong>; Minor in Computer Science ∙ University of Virginia ∙ 2024
  </li>
</ul>

## Interests
Beyond the professional sphere, I’m most fulfilled by hobbies that blend creativity with a deep sense of exploration and discovery. Whether I’m delving into European monarchal history or crafting through embroidery and crochet, I enjoy activities that engage both my hands and my mind. I find the most joy in cooking and baking, where creativity meets intuition and curiosity. It’s a process of experimentation, adaptability, and creating something meaningful to share with others—a perfect balance of structure and spontaneity. This same fascination with shaping outcomes draws me to life simulation and narrative-driven games like *The Sims*, *Life is Strange*, and *Detroit: Become Human*. These games, much like cooking, require thoughtful decisions and invite you to explore how small choices can lead to vastly different results. I’m continually inspired by pursuits that challenge me to think creatively, build connections, and embrace new perspectives.




